// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_tokens.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createRefreshTokenForUser = `-- name: CreateRefreshTokenForUser :one
 INSERT INTO refresh_tokens(token, expires_at, revoked_at, created_at, updated_at, user_id)
 VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
 ) RETURNING token, expires_at, revoked_at, user_id, created_at, updated_at
`

type CreateRefreshTokenForUserParams struct {
	Token     string       `json:"token"`
	ExpiresAt time.Time    `json:"expires_at"`
	RevokedAt sql.NullTime `json:"revoked_at"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	UserID    uuid.UUID    `json:"user_id"`
}

func (q *Queries) CreateRefreshTokenForUser(ctx context.Context, arg CreateRefreshTokenForUserParams) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, createRefreshTokenForUser,
		arg.Token,
		arg.ExpiresAt,
		arg.RevokedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UserID,
	)
	var i RefreshToken
	err := row.Scan(
		&i.Token,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTokenbyToken = `-- name: GetTokenbyToken :one
 SELECT token, expires_at, revoked_at, user_id, created_at, updated_at FROM refresh_tokens
 WHERE token = $1
`

func (q *Queries) GetTokenbyToken(ctx context.Context, token string) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, getTokenbyToken, token)
	var i RefreshToken
	err := row.Scan(
		&i.Token,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeToken = `-- name: RevokeToken :exec
UPDATE refresh_tokens
SET revoked_at = $2,
    updated_at = $3
WHERE token = $1
`

type RevokeTokenParams struct {
	Token     string       `json:"token"`
	RevokedAt sql.NullTime `json:"revoked_at"`
	UpdatedAt time.Time    `json:"updated_at"`
}

func (q *Queries) RevokeToken(ctx context.Context, arg RevokeTokenParams) error {
	_, err := q.db.ExecContext(ctx, revokeToken, arg.Token, arg.RevokedAt, arg.UpdatedAt)
	return err
}
